### ISSUE TITLE
blocked on wifi

### ISSUE THREAD

**Issue by loglot** [TodePond/TadiWeb#2]
my school wifi decides to block tadiweb, i can just use a vpn, but why is this happening?

**Comment by TodePond** [comment]
probably because it's too niche. to fix the issue, follow these steps:

* wait until you're older
* try again on your own internet

**Comment by loglot** [comment]
It's just weird, because everything else works, I do have my own wifi, but I need to go to a school that costs too much

**Comment by loglot** [comment]
the issue was probably because it was too new
